---
app-template:
  global:
    fullnameOverride: "overseerr"

  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          image:
            repository: sctx/overseerr
            tag: "latest"
          env:
            TZ: "America/Los_Angeles"

  service:
    main:
      ports:
        http:
          port: 5055

  ingress:
    main:
      enabled: true
      annotations: {}
      hosts:
        - host: overseerr.example.local
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls: []
      #  - secretName: overseerr-example-tls
      #    hosts:
      #      - overseerr.example.local

  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /app/config
